salsadigitalauorg/ckanext-qdes-schema

- ckanext/qdes_schema/fanstatic/repeating-fields.js
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_textarea.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_textarea.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
https://it-partners.atlassian.net/browse/DDCI-35
- added field config
- added/modified 2 form snippet for multi text and textarea
- added display snippet for text and text area
- hide and show based on the g.debug variable.
> [DDCI-35] - added identifiers field

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/display_snippets/datetime_tz.html
- ckanext/qdes_schema/templates/scheming/form_snippets/datetime_tz.html
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-22
I also updated the time datepicker to allow step=1
> [DDCI-22] - added publication status and update schedule fields

- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-120
> [DDCI-120] - added rights and landing page

- ckanext/qdes_schema/fanstatic/q_des.css
- ckanext/qdes_schema/fanstatic/repeating-fields.js
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/templates/base.html
- ckanext/qdes_schema/templates/scheming/display_snippets/markdown.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_markdown.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_markdown.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_textarea.html
https://it-partners.atlassian.net/browse/DDCI-116
- Added new preset 'controlled_vocabulary_multi_select'
- Updated repeater to handle multiple select 'autocomplete' elements
- Added 'q_des.css' to base page template
- Updated description group metadata
> [DDCI-116] Dataset fields (baseline) - AC 3 a. to g.

- ckanext/qdes_schema/validators.py
> added defensive coding

- ckanext/qdes_schema/plugin.py
> added defensive coding on repeatable JSON field

- ckanext/qdes_schema/fanstatic/q_des.css
- ckanext/qdes_schema/fanstatic/repeating-fields.js
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/package/snippets/resource_info.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_byte_size.html
- ckanext/qdes_schema/templates/scheming/form_snippets/textarea.html
- ckanext/qdes_schema/templates/scheming/package/resource_read.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-13
> [DDCI-13] - added resource fields

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/form_snippets/datetime_tz.html
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-22
- added default value to DateTime field.
> [DDCI-22] - qa fixes around validation

- ckanext/qdes_schema/fanstatic/autocomplete.js
- ckanext/qdes_schema/fanstatic/q_des.css
- ckanext/qdes_schema/fanstatic/repeating-fields.js
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/templates/base.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_group_select.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_markdown.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_textarea.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group_select.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/validators.py
- Added preset 'controlled_vocabulary_multi_group_select' to add groups of multi select elements
- Added 'qdes_validate_multi_groups' to validate multi-groups values are not missing
- Updated 'repeating-fields.js' to handle multi groups
> [DDCI-117] Dataset fields (baseline) - AC 3 item h.

- ckanext/qdes_schema/fanstatic/autocomplete.js
https://it-partners.atlassian.net/browse/DDCI-7
the autocomplete was not working for all fields in my local, it seems race condition issue. I wrapped them in jquery document ready thing and it seems the issue in my local.
> [DDCI-7] - fix race condition issue on auto complete.

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/display_snippets/text.html
- ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-35
https://it-partners.atlassian.net/browse/DDCI-13
@salsa-nathan I have to merge https://github.com/salsa-nathan/ckanext-qdes-schema/pull/19 to this branch, because when I have value of spatial fields it always throw an error without it.
> [DDCI-32-13] - schema update

- ckanext/qdes_schema/qdes_ckan_dataset.json
https://it-partners.atlassian.net/browse/DDCI-10
> [DDCI-10] - added lineage fields

- ckanext/qdes_schema/logic/action/update.py
- ckanext/qdes_schema/logic/helpers/dataservice_helpers.py
- ckanext/qdes_schema/logic/helpers/resource_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/plugin_resources.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/templates/scheming/display_snippets/controlled_vocabulary_single_select.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/validators.py
- setup.py
https://it-partners.atlassian.net/browse/DDCI-14
- added bunch of fields
- currently, only when you edit/add dataset, the `datasets available` field will be populated, the existing URL on `datasets available` won't be removed.
> [DDCI-14] - added baseline for dataservice

- ckanext/qdes_schema/fanstatic/repeating-fields.js
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html
https://it-partners.atlassian.net/browse/DDCI-32
@salsa-nathan I am using `alert-warning` class as per solution direction, this has yellow color instead of the red color.
> [DDCI-32] - added superseded alert box

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/logic/action/get.py
- ckanext/qdes_schema/logic/helpers/relationship_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/read.html
- ckanext/qdes_schema/templates/package/snippets/dataset_versions.html
https://it-partners.atlassian.net/browse/DDCI-15
> [DDCI-15] - list dataset versions

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/logic/action/get.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/package/read.html
- ckanext/qdes_schema/templates/package/snippets/dataset_related.html
- ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
https://it-partners.atlassian.net/browse/DDCI-71
> [DDCI-71] - added data lineage fields and related fields

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_text_url.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_text_url.html
https://it-partners.atlassian.net/browse/DDCI-10
added conditional for value, either print as text or link.
> [DDCI-10] - added ckan url validator to plan field

- ckanext/qdes_schema/qdes_ckan_dataset.json
https://it-partners.atlassian.net/browse/DDCI-114
https://it-partners.atlassian.net/browse/DDCI-126
https://it-partners.atlassian.net/browse/DDCI-127
> [DDCI-126-127-114] - updated schema

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/read.html
- ckanext/qdes_schema/templates/package/read_base.html
- ckanext/qdes_schema/templates/package/related_datasets.html
https://it-partners.atlassian.net/browse/DDCI-16
> [DDCI-16] - added new related datasets tabs

- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_group.html
- check for empty `group_data`
- closed <div>
> [DDCI-9] Fix for empty `group_data` values

- ckanext/qdes_schema/logic/action/get.py
https://it-partners.atlassian.net/browse/DDCI-16
> [DDCI-16] - updated ordering to ascending for creation date

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/package/metadata.html
- ckanext/qdes_schema/templates/package/read_base.html
- ckanext/qdes_schema/templates/scheming/package/resource_metadata.html
- ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
- ckanext/qdes_schema/templates/scheming/package/snippets/metadata_additional_info.html
https://it-partners.atlassian.net/browse/DDCI-6
**with few empty fields**
**with complete fields**
**with few empty fields**
**with complete fields**
dataset resource metadata
> [DDCI-6] - added view all metadata for dataset and resource

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/search.html
https://it-partners.atlassian.net/browse/DDCI-70
> [DDCI-70] - showed the spatial search

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/admin/config.html
- ckanext/qdes_schema/templates/package/search.html
https://it-partners.atlassian.net/browse/DDCI-70
added QLD bounding box
> [DDCI-70] added qld bb

- ckanext/qdes_schema/logic/helpers/indexing_helpers.py
- ckanext/qdes_schema/plugin.py
Store the label values for each dataset resource so that they can be indexed in Solr.
> [DDCI-67] Added search on resource format labels.

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/package/resource_metadata.html
- ckanext/qdes_schema/templates/scheming/package/resource_read.html
- ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
https://it-partners.atlassian.net/browse/DDCI-6
> [DDCI-6] - adjusted display

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/templates/scheming/display_snippets/text.html
https://it-partners.atlassian.net/browse/DDCI-166
https://it-partners.atlassian.net/browse/DDCI-171
> [DDCI-166-171] accept odrl value

- ckanext/qdes_schema/qdes_ckan_dataset.json
https://it-partners.atlassian.net/browse/DDCI-147
> [DDCI-147] - added quality measurement

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
https://it-partners.atlassian.net/browse/DDCI-209
> [DDCI-209] - updated label

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_text_url.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_text_url.html
https://it-partners.atlassian.net/browse/DDCI-171
I added a helper to replace URL within a string to link (<a href>)
> [DDCI-171] - added regex to detect and replace url to link within text

- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-202
https://it-partners.atlassian.net/browse/DDCI-203
I also fix an issue on validation.
> [DDCI-202] - added new validation for last modified date and fix issue

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/read.html
- ckanext/qdes_schema/templates/scheming/package/resource_read.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
- ckanext/qdes_schema/templates/snippets/invalid_uris_error.html
https://it-partners.atlassian.net/browse/DDCI-167
**please merge https://github.com/salsadigitalauorg/ckanext-invalid-uris/pull/1 first, otherwise, it will throw errors**
> [DDCI-167] - added UI for invalid uris

- ckanext/qdes_schema/fanstatic/repeating-fields.js
https://it-partners.atlassian.net/browse/DDCI-147
the error was due to null value being added as json.
> [DDCI-147] - excluded null value from multigroups field

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/fanstatic/dataservice.js
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/logic/helpers/dataset_helpers.py
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/templates/package/available_datasets.html
- ckanext/qdes_schema/templates/package/base.html
- ckanext/qdes_schema/templates/package/base_form_page.html
- ckanext/qdes_schema/templates/package/read_base.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- Added new tab 'Available Datasets' for data services
- Removed resources for data services
- Changed save button text for data services
- Removed stages ribbon for data services
> Feature/ddci 163 data service   remove 'add data' page when creating new data services

- ckanext/qdes_schema/templates/package/edit.html
- ckanext/qdes_schema/templates/package/read.html
https://it-partners.atlassian.net/browse/DDCI-163
> [DDCI-163] - removed resources tab on edit and on read

- ckanext/qdes_schema/fanstatic/repeating-fields.js
Updated 'secure-autocomplete' to only store 'id' value instead of the whole json object
> https://it-partners.atlassian.net/browse/DDCI-50 QA Remediation 

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/qld_harverst/dataset.csv
- ckanext/qdes_schema/qld_harverst/import.py
https://it-partners.atlassian.net/browse/DDCI-30
error example:
```[{'errors': {'__type': 'Validation Error',
'name': ['That URL is already in use.']},
'package_id': 'sali-soil-chemistry-api'},
{'errors': {'__type': 'Validation Error',
'name': ['That URL is already in use.']},
'package_id': 'protected-areas-of-queensland-series'},
{'errors': {'__type': 'Validation Error',
'name': ['That URL is already in use.']},
'package_id': 'matters-of-state-environmental-significance-queensland-series'},
{'errors': ['Not able to load the package from source.'],
'package_id': 'heritage-register-boundaries-queensland--sss'},
{'errors': ['Not able to load the package from source.'],
'package_id': 'heritage-register-boundaries-queensland--sss'},
{'errors': {'__type': 'Validation Error',
'name': ['That URL …
```
> [DDCI-30] - added harvest from QLD

- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html
- ckanext/qdes_schema/templates/scheming/snippets/errors.html
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-178
Setup: "version 1" isReplacedBy "version 2"
add/edit "version 3". `replaces` relationship
Edit "version 1", `isReplacedBy` relationship
Updated error msg
> [DDCI-178] - added replace relationship validation

- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-178
> [DDCI-178] fixes when creating a new dataset

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/validators.py
- Added `ignore_missing` to a lot of fields as they were causing API package_create requests to fail for missing values, but not required fields
- Added try/except around the temporal date validator for cases when temporal dates are not supplied
> Validator changes

- ckanext/qdes_schema/logic/helpers/relationship_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/read.html
https://it-partners.atlassian.net/browse/DDCI-177
> [DDCI-177] - added notif if prev version not superseded

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
https://it-partners.atlassian.net/browse/DDCI-234
https://it-partners.atlassian.net/browse/DDCI-237
https://it-partners.atlassian.net/browse/DDCI-238
https://it-partners.atlassian.net/browse/DDCI-239
> [DDCI-234 237 238 239] updated fields

- ckanext/qdes_schema/plugin.py
- Remove `ignore_auth` from context if set by relationships auth function
> [DDCI-243] Allow relationships across all orgs

- ckanext/qdes_schema/helpers.py
https://it-partners.atlassian.net/browse/DDCI-193
> [DDCI-193] - displayed forward relationship types only

- ckanext/qdes_schema/logic/helpers/indexing_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/search.html
- ckanext/qdes_schema/templates/snippets/spatial_query.html
https://it-partners.atlassian.net/browse/DDCI-69
> [DDCI-69] - added custom facet

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_select.html
- ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
https://it-partners.atlassian.net/browse/DDCI-355
https://it-partners.atlassian.net/browse/DDCI-341
> [DDCI-355-341] - updated schema and print id

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/logic/helpers/indexing_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/read.html
- ckanext/qdes_schema/templates/package/search.html
- ckanext/qdes_schema/templates/snippets/collection.html
https://it-partners.atlassian.net/browse/DDCI-17
> [DDCI-17] - added collection notification and search series feature

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
https://it-partners.atlassian.net/browse/DDCI-355
reverted the dataset, turned out the solution direction is not accurate and I didn't do double-check the AC.
> [DDCI-355] - recommended field for dataservice

- ckanext/qdes_schema/templates/snippets/collection.html
https://it-partners.atlassian.net/browse/DDCI-17
> [DDCI-17] - updated wording

- ckanext/qdes_schema/templates/package/metadata.html
https://it-partners.atlassian.net/browse/DDCI-341
> [DDCI-341] - added ckan id to all metadata page

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
https://it-partners.atlassian.net/browse/DDCI-175
> [DDCI-175] - added validator to identifier

- ckanext/qdes_schema/templates/package/schema_validation.html
https://it-partners.atlassian.net/browse/DDCI-139
I forgot to commit and push this code after creating a PR, below to fix the success msg appear on load.
> [DDCI-139] - hide success msg

- ckanext/qdes_schema/logic/helpers/resource_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/plugin_resources.py
https://it-partners.atlassian.net/browse/DDCI-385
> [DDCI-385] - refactored functions

- ckanext/qdes_schema/fanstatic/dataset_no_resource.js
- ckanext/qdes_schema/fanstatic/style.css
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
https://it-partners.atlassian.net/browse/DDCI-394
> [DDCI-394] - added save record button

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/admin/config.html
- ckanext/qdes_schema/templates/snippets/spatial_query.html
https://it-partners.atlassian.net/browse/DDCI-88
> [DDCI-88] - added default zoom and changed label

- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-411
> [DDCI-411] - added centroid to spatial field when no lower left and upper right

- ckanext/qdes_schema/templates/package/base_form_page.html
https://it-partners.atlassian.net/browse/DDCI-240
> [DDCI-240] - updated descriptive text

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/text.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
- ckanext/qdes_schema/templates/scheming/snippets/form_field.html
- ckanext/qdes_schema/templates/snippets/invalid_uris_error.html
https://it-partners.atlassian.net/browse/DDCI-235
> [DDCI-235] - added error msg below the field

- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
https://it-partners.atlassian.net/browse/DDCI-235
regression issue: invalid_uris should be on edit not new.
> [DDCI-235] -  fix regression issue

- ckanext/qdes_schema/fanstatic/temporal-coverage.css
- ckanext/qdes_schema/fanstatic/temporal-coverage.js
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/search.html
- ckanext/qdes_schema/templates/snippets/facet_list_temporal.html
https://it-partners.atlassian.net/browse/DDCI-367
> [DDCI-367] - added temporal coverage facet

- ckanext/qdes_schema/plugin.py
https://it-partners.atlassian.net/browse/DDCI-383
> [DDCI-383] - fix regression issue on package create

- ckanext/qdes_schema/auth.py
- ckanext/qdes_schema/plugin.py
https://it-partners.atlassian.net/browse/DDCI-221
> [DDCI-221] - dataservice access

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/templates/package/metadata.html
- ckanext/qdes_schema/templates/scheming/package/resource_metadata.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
- ckanext/qdes_schema/templates/snippets/invalid_uris_error.html
https://it-partners.atlassian.net/browse/DDCI-242
> [DDCI-242] - updated wording

- ckanext/qdes_schema/qdes_ckan_dataset.json
https://it-partners.atlassian.net/browse/DDCI-454
> [DDCI-454] - changed primary format dropdown

- ckanext/qdes_schema/helpers.py
https://it-partners.atlassian.net/browse/DDCI-449
it seems the uri is the only one connecting them. the value on develop has space
> [DDCI-449] - added definitions to relationship

- ckanext/qdes_schema/templates/snippets/invalid_uris_error.html
Updated wording as per discussion with Emil
> [DDCI-242] - updated error message

- ckanext/qdes_schema/fanstatic/qdes-tree-selector.js
- ckanext/qdes_schema/qdes_dataservice.json
https://it-partners.atlassian.net/browse/DDCI-244
> [DDCI-244] - added tooltip and counter

- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree_multi_group.html
https://it-partners.atlassian.net/browse/DDCI-244
> [DDCI-244] - updated markup

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/constants.py
- ckanext/qdes_schema/fanstatic/publish.js
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/model.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/publish_metadata.html
- ckanext/qdes_schema/templates/package/snippets/external_publishing_details.html
- ckanext/qdes_schema/templates/package/snippets/validate_and_publish_metadata.html
https://it-partners.atlassian.net/browse/DDCI-356
for context https://github.com/salsa-nathan/ckanext-qdes-schema/pull/113
> [DDCI-356] - added publish activity screen

- ckanext/qdes_schema/fanstatic/qdes-tree-selector.js
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree_multi_group.html
https://it-partners.atlassian.net/browse/DDCI-244
> [DDCI-244] - fix typo and sizing

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/templates/admin/config.html
https://it-partners.atlassian.net/browse/DDCI-487
the solution didn't follow the SD, had discussion with Emil and decided to put it inside config tab instead of new tab.
> [DDCI-487] - replaced publishing portal

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/fanstatic/publish.js
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
- ckanext/qdes_schema/model.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/publish_metadata.html
- ckanext/qdes_schema/templates/package/read_base.html
- ckanext/qdes_schema/templates/package/snippets/external_publishing_details.html
- ckanext/qdes_schema/templates/package/snippets/unpublish_external_dataset.html
- ckanext/qdes_schema/templates/package/snippets/validate_and_publish_metadata.html
https://it-partners.atlassian.net/browse/DDCI-401
> [DDCI-401] - added unpublish dataset

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/templates/admin/config.html
hotfix for resource add/edit form.
so the issue was this qdes_dataservice_choices was used for choice_helper in json file, and it needs a param.
I removed it because it was unused param, but I didn't notice this until the error :(,
> re-added required paramter

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
https://it-partners.atlassian.net/browse/DDCI-74
https://it-partners.atlassian.net/browse/DDCI-569
all fields now pointing to point-of contact secure vocab.
> [DDCI-74] - added new search display

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/dataqld_dataset.json
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/logic/action/get.py
- ckanext/qdes_schema/logic/helpers/resource_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/qspatial_dataset.json
- ckanext/qdes_schema/sir_dataset.json
- ckanext/qdes_schema/templates/scheming/form_snippets/state_select.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
https://it-partners.atlassian.net/browse/DDCI-572
I combined both stories because the 392 has 572's AC,
also, updated other schema so that in future we don't need to re-compare those json.
> [DDCI-392] - added deletion scenarios

- ckanext/qdes_schema/fanstatic/repeating-fields.js
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
https://it-partners.atlassian.net/browse/DDCI-572
> [DDCI-572] - added other states and hide them

- ckanext/qdes_schema/qdes_dataservice.json
https://it-partners.atlassian.net/browse/DDCI-572
> [DDCI-572] - updated schema for dataservice

- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
https://it-partners.atlassian.net/browse/DDCI-569
> [DDCI-569] - fix delete button on multi text

- ckanext/qdes_schema/helpers.py
fix regression issue when other non sysadmin user visit dashboard
> [DDCI-59] - fix dashboard error for non admin

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/logic/action/get.py
- ckanext/qdes_schema/logic/helpers/indexing_helpers.py
- ckanext/qdes_schema/logic/helpers/relationship_helpers.py
- ckanext/qdes_schema/templates/snippets/collection.html
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-449
> [DDCI-449] - updated relationship labels

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/logic/action/delete.py
- ckanext/qdes_schema/logic/action/get.py
- ckanext/qdes_schema/logic/helpers/resource_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/read.html
- ckanext/qdes_schema/templates/package/snippets/dataset_versions.html
- ckanext/qdes_schema/templates/package/snippets/info.html
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/snippets/collection.html
- ckanext/qdes_schema/validators.py
- moved `delete` label to dedicated helper
- fix issues on various location where pkg title printed.
- listened to purge and purge all 
-
> [DDCI-392] - added more delete label and listen to purge

- ckanext/qdes_schema/dataqld_dataset.json
- ckanext/qdes_schema/qspatial_dataset.json
- ckanext/qdes_schema/sir_dataset.json
https://it-partners.atlassian.net/browse/DDCI-74
> [DDCI-74] - updated schema so it won't fail validation for external

- ckanext/qdes_schema/templates/package/metadata.html
- ckanext/qdes_schema/templates/package/snippets/lifecycle.html
https://it-partners.atlassian.net/browse/DDCI-87
> [DDCI-87] - added lifecycle

- ckanext/qdes_schema/helpers.py
https://it-partners.atlassian.net/browse/DDCI-356
> [DDCI-356] - keep unpublish to show when dataset/distribution needs update

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
- ckanext/qdes_schema/logic/helpers/resource_helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/package/snippets/external_publishing_details.html
- ckanext/qdes_schema/templates/snippets/activities/unpublish_external_schema.html
https://it-partners.atlassian.net/browse/DDCI-149
added context, wrap the process in try except to capture the error minimalize the hanging pending status, and prevent republish for deleted dataset
> [DDCI-149] - prevented from republishing

- ckanext/qdes_schema/fanstatic/help-text.js
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/templates/scheming/form_snippets/help_text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/organization.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_duration.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
https://it-partners.atlassian.net/browse/DDCI-229
- so I use js to help the setup, instead of modifying too many macros, also there are multiple position of help text (next to label, next to heading, next to sub heading)
> [DDCI-229] - added helptext

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/select.html
- ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree.html
https://it-partners.atlassian.net/browse/DDCI-677
> [DDCI-677] - updated field placeholder

- ckanext/qdes_schema/templates/snippets/activities/changed_package.html
- ckanext/qdes_schema/templates/snippets/activities/new_package.html
- ckanext/qdes_schema/templates/snippets/activity_stream.html
https://it-partners.atlassian.net/browse/DDCI-353
so the idea is, I added `first_item=loop.first` to the activity_stream.html so the snippet can know if he is the first one.
> [DDCI-353] - fix first activity stream to link to recent

- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-199
> [DDCI-199] - added validation for forward relationship

- ckanext/qdes_schema/logic/action/delete.py
- ckanext/qdes_schema/logic/helpers/resource_helpers.py
- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_group.html
> [DDCI-392] - displayed correct deteled pkg title and added try except

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
- Updated publishing to Open Data Portal
- Added mapping from QDes licenses to Data.QLD licenses
> [DDCI-707]

- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-199
> [DDCI-199] - accepted forward relationship on create/update/patch

- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
updated error msg for resource
> [DDCI-392] - updated error msg

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
- ckanext/qdes_schema/logic/helpers/resource_helpers.py
I am refactoring the `resource_helpers.add_dataservice` function. 
I am not sure what happening here tbh.
> [DDCI-392] refactored resource_update action

- ckanext/qdes_schema/dataqld_dataset.json
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/logic/action/update.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/qspatial_dataset.json
- ckanext/qdes_schema/sir_dataset.json
- ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_markdown.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_select.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_textarea.html
https://it-partners.atlassian.net/browse/DDCI-791
> [DDCI-791] - updated dataset related fields

- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-855
> [DDCI-855] - fix internal error resource field is not set

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
https://it-partners.atlassian.net/browse/DDCI-789
> [DDCI-789] added asterisk to accordion

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
Add new schema field `sub_heading_info_text` 
Display the text under the h3 heading
> [DDCI-790] Add additional help text and link to Spatial Coverage section

- ckanext/qdes_schema/qdes_presets.json
Switch label to use Related Datasets
> [DDCI-854] Change warning / error messages to match the changes to "Related datasets"

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
https://it-partners.atlassian.net/browse/DDCI-858
https://it-partners.atlassian.net/browse/DDCI-848
https://it-partners.atlassian.net/browse/DDCI-859
> [DDCI-858] enhanced publish log status

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
Mapping helper method for primary formats
> [DDCI-738] Map catalogue primary formats to Data.QLD formats to allow publishing to QLD open data portal

- ckanext/qdes_schema/qdes_ckan_dataset.json
Change help link text in schema
> [DDCI-885] Change help link

- ckanext/qdes_schema/templates/scheming/display_snippets/qdes_secure_vocabulary_text.html
Set message to `No person assigned` if there is nothing to display
> [DDCI-836] Unresolved point of contact

- ckanext/qdes_schema/jobs.py
https://it-partners.atlassian.net/browse/DDCI-964
this will be reverted in future, see ticket for more details
> [DDCI-964] - set private to true when publishing to dataqld

- ckanext/qdes_schema/blueprint.py
https://it-partners.atlassian.net/browse/DDCI-874
> [DDCI-874] - added ispartof and haspart relationship

- ckanext/qdes_schema/fanstatic/input-date-helper.js
- ckanext/qdes_schema/fanstatic/qdes-tree-selector.js
- ckanext/qdes_schema/fanstatic/style.css
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/templates/scheming/form_snippets/date.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree_multi_group.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
https://it-partners.atlassian.net/browse/DDCI-889
> [DDCI-889] - added clear button next to fields

- ckanext/qdes_schema/templates/package/export/XML (ISO-19139).xml.j2
> [DDCI-140] - fix xml format

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/templates/package/export/XML (ISO-19139).xml.j2
> [DDCI-140] - updated xml

- ckanext/qdes_schema/plugin.py
https://it-partners.atlassian.net/browse/DDCI-967
the indexing was throwing an error due to the field on dataservice and dataset are slightly different, added a check if the field is there, then execute the indexing
> [DDCI-967] - added check for the indexing

- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-289
> [DDCI-289] - added validation for positive numbers

- ckanext/qdes_schema/templates/package/metadata.html
https://it-partners.atlassian.net/browse/DDCI-891
> [DDCI-891] - added private label

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/templates/package/export/XML (ISO-19139).xml.j2
pretty print, hide empty values.
> [DDCI-140] - updated xml export and pretty print

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/templates/package/export/XML (ISO-19139).xml.j2
https://it-partners.atlassian.net/browse/DDCI-140?focusedCommentId=273359
> [DDCI-140] - added missing fields

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/templates/package/export/XML (ISO-19139).xml.j2
re-indent the template, and adjusted few fields
> [DDCI-140] - updated xml export format and add new fields

- ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
- ckanext/qdes_schema/templates/snippets/dataset_map_qdes.html
- ckanext/qdes_schema/templates/snippets/dataset_spatial_table.html
https://it-partners.atlassian.net/browse/DDCI-181
> [DDCI-181] - added spatial display on dataset

- ckanext/qdes_schema/templates/snippets/dataset_spatial_table.html
https://it-partners.atlassian.net/browse/DDCI-181
> [DDCI-181] - hide map when no centroid or bounding box

- ckanext/qdes_schema/jobs.py
https://it-partners.atlassian.net/browse/DDCI-975
> [DDCI-975] revert publish visibility

- ckanext/qdes_schema/blueprint.py
Dont appaend empty dataservices to the XML export file
> [DDCI-976] fix export empty dataservice

- ckanext/qdes_schema/templates/package/snippets/validate_and_publish_metadata.html
https://it-partners.atlassian.net/browse/DDCI-979
> [DDCI-979] - fixed series detexction

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/fanstatic/dataset_no_resource.js
https://it-partners.atlassian.net/browse/DDCI-989
- Override CKAN core dataset view class CreateView
- Add logic to save dataset in draft state when the 'Finish: Save record' is clicked and redirect to dataset read page
> [DDCI-989] Draft copy of dataset is created that can't be deleted

- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/group/read.html
- ckanext/qdes_schema/templates/organization/read.html
- ckanext/qdes_schema/templates/snippets/facet_list_temporal.html
- ckanext/qdes_schema/templates/snippets/spatial_query.html
https://salsadigital.atlassian.net/browse/SUPDESQ-21
the `dataset` param at `return self.dataset_facets(facets_dict, 'dataset')` is to make sure the facet same as /dataset page
> [SUPDESQ-21] added facet to cat and org

- ckanext/qdes_schema/plugin.py
Change the query to use `OR` instead of  `AND`
> [SUPDESQ-31] Temporal search

- ckanext/qdes_schema/plugin.py
Name or Code added as facet in search
> [SUPDESQ-32] Name or Code

- ckanext/qdes_schema/plugin.py
Add helper for converting uri to label
> [SUPDESQ-33] Temporal and spatial details

- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/validators.py
https://salsadigital.atlassian.net/browse/SUPDESQ-25
> [SUPDESQ-25] - added extra validators to schema

- ckanext/qdes_schema/constants.py
[SUPDESQ-51] Change republish to republishing
> [SUPDESQ-51] Change message

- ckanext/qdes_schema/templates/snippets/dataset_spatial_table.html
https://salsadigital.atlassian.net/browse/SUPDESQ-69
> [SUPDESQ-69] render geometry map

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/templates/package/read_base.html
Remove publish tab for dataservice
> [SUPDESQ-38] Remove publish dataservice

- ckanext/qdes_schema/fanstatic/accordion.js
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
Enable 'ENTER' or 'SPACE' to toggle accordion expand
> [SUPDESQ-52] keyboard shortcuts

- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree.html
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree_multi_group.html
Use the btn-secondary class for qdes-tree add button
> [SUPDESQ-46] Change button color

- ckanext/qdes_schema/qdes_ckan_dataset.json
https://salsadigital.atlassian.net/browse/SUPDESQ-25
> [SUPDESQ-25] - added remove whitespave to notes validators

- ckanext/qdes_schema/plugin.py
Move the facet under temporal search
Rename the label to 'Geographic name`
> [SUPDESQ-32] Fix from QA comments

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/package/snippets/unpublish_external_dataset.html
Bulk resource unpublishing enabled
> [SUPDESQ-37] Unpublish all

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/validators.py
https://salsadigital.atlassian.net/browse/SUPDESQ-39
in this PR.
- updated existing validator to calculate the bounding box of the geometry. and add them to lower left and upper right.
- implement the spatial map input module
> [SUPDESQ-39] - added the spatial map input form and geometry validation

- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/package/available_datasets.html
https://salsadigital.atlassian.net/browse/SUPDESQ-72
> [SUPDESQ-72] updated data service label

- ckanext/qdes_schema/plugin.py
https://salsadigital.atlassian.net/browse/SUPDESQ-73
> [SUPDESQ-73] added new filter for temporal coverage

- ckanext/qdes_schema/fanstatic/qdes-tree-selector.js
- ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/select.html
https://salsadigital.atlassian.net/browse/SUPDESQ-35
> [SUPDESQ-35] - added support for quantity kind

- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
https://salsadigital.atlassian.net/browse/SUPDESQ-34
do not merge
> [SUPDESQ-34] - updated vocab name for license fields

- ckanext/qdes_schema/fanstatic/spinner.js
- ckanext/qdes_schema/fanstatic/webassets.yml
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
Add spinner while JS are loading
> [SUPDESQ-47] Prevent js 

- ckanext/qdes_schema/fanstatic/qdes-tree-selector.js
https://salsadigital.atlassian.net/browse/SUPDESQ-35
> [SUPDESQ-35] - fix issue when grouping quantity kinds

- ckanext/qdes_schema/dataqld_dataset.json
Update the `dataqld_dataset.json` schema with values from `qdes_ckan_dataset.json` schema
> [SUDPESQ-37] Unable to publish

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/fanstatic/publish.js
- ckanext/qdes_schema/templates/package/snippets/unpublish_external_dataset.html
> [SUPDESQ-37] Unpublish issues

- ckanext/qdes_schema/fanstatic/spinner.js
https://salsadigital.atlassian.net/browse/SUPDESQ-47
> [SUPDESQ-47] - fix spinner issue

- ckanext/qdes_schema/fanstatic/qdes-tree-selector.js
https://salsadigital.atlassian.net/browse/SUPDESQ-35
- removed dimensionless
- disabled recursive by default
> [SUPDESQ-35] removed recursive and dimensionless

- ckanext/qdes_schema/dcat/profiles.py
- ckanext/qdes_schema/templates/package/metadata.html
- setup.py
https://salsadigital.atlassian.net/browse/SUPDESQ-29
https://salsadigital.atlassian.net/browse/SUPDESQ-67
> [SUPDESQ-29] - added mapping for RDF

- ckanext/qdes_schema/templates/package/metadata.html
Remove XML export
RDF export by dataset name
> [SUPDESQ-67] Remove xml export

- ckanext/qdes_schema/dcat/profiles.py
- ckanext/qdes_schema/templates/package/metadata.html
Fix for  QualityAnnotation and QualityMeasurement
> [SUPDESQ-29] Remediation

- ckanext/qdes_schema/dataqld_dataset.json
- ckanext/qdes_schema/dcat/profiles.py
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/qdes_dataservice.json
- ckanext/qdes_schema/qdes_presets.json
- ckanext/qdes_schema/qspatial_dataset.json
- ckanext/qdes_schema/sir_dataset.json
- ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree_multi_group.html
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
Fix for the nature of relationship vocabulary_service_name
Includes fix for [SUPDESQ-93]
> [SUPDESQ-91] Nature of relationship

- ckanext/qdes_schema/qdes_dataservice.json
replace dataset with dataservice
> [SUPDESQ-49] qa fix

- ckanext/qdes_schema/qdes_dataservice.json
Change dataservice's `contact_point` help text
> [SUPDESQ-49] qa fix 

- ckanext/qdes_schema/qdes_dataservice.json
Update the presets for `point-of-contact` and `metada-point-of-contact` for dataservice
> [SUPDESQ-94] Point of contact for dataservice

- ckanext/qdes_schema/fanstatic/qdes-tree-selector.js
Disappearing text when the value required is missing from the select
> [SUPDESQ-99] Disapearing text

- ckanext/qdes_schema/jobs.py
- ckanext/qdes_schema/logic/helpers/resource_helpers.py
Fixed issue with dataset identifiers getting overridden with blank value when adding dataservice to resource
Remove identifier if the dataset is deleted from the source
Refactored and cleaned up code
> SUPDESQ-98-Defect - Cloned datasets are not published correctly

- ckanext/qdes_schema/qdes_ckan_dataset.json
> [SUPDESQ-104] Help text

- ckanext/qdes_schema/dcat/profiles.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
> [SUPDESQ-29] Remediation work

- ckanext/qdes_schema/dcat/profiles.py
Fixes for RDF exports for dataset and dataservice
> [SUPDESQ-29] RDF export fix

- ckanext/qdes_schema/dcat/profiles.py
Fix issues with duplicate methadata modified
> [SUPDESQ-67] Remediation 

- ckanext/qdes_schema/dcat/profiles.py
- [T3 Support - Export metadata records via RDF / TTL](https://salsadigital.atlassian.net/browse/SUPDESQ-29)
- [T3 Support - Data Service - Enable Export functionality for a data service](https://salsadigital.atlassian.net/browse/SUPDESQ-67)
> [SUPDESQ-67][SUPDESQ-29] QA Remediation

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
Show the activity data from history when clicking the show metadata link
> [SUPDESQ-101] Show activity data

- ckanext/qdes_schema/dcat/profiles.py
- ckanext/qdes_schema/qdes_ckan_dataset.json
- ckanext/qdes_schema/templates/scheming/form_snippets/textarea.html
Show current year in the placeholder for the rights statement field
> [SUPDESQ-103]Show current year in the placeholder

- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
- ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
- ckanext/qdes_schema/templates/snippets/invalid_uris_error.html
Adding new Interface from IInvalidURIs to get contact point data
> Removed duplication of code which is in extension ckanext-invalid-uris

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/constants.py
- ckanext/qdes_schema/fanstatic/publish.js
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
- ckanext/qdes_schema/model.py
- ckanext/qdes_schema/plugin.py
- ckanext/qdes_schema/qld_cdp_dataset.json
- ckanext/qdes_schema/templates/admin/config.html
- ckanext/qdes_schema/templates/package/snippets/unpublish_external_dataset.html
- ckanext/qdes_schema/templates/snippets/activities/publish_external_schema.html
- ckanext/qdes_schema/templates/snippets/activities/unpublish_external_schema.html
This release includes:
- [SUPDESQ-111: Publish to Queensland Government Closed Data Portal](https://salsadigital.atlassian.net/browse/SUPDESQ-111)
> UAT Release: Publishing to QLD CDP

- ckanext/qdes_schema/templates/package/snippets/unpublish_external_dataset.html
This pull request adds a confirmation message to the unpublish button in the unpublish-wrapper section. 
It also formats the document for better readability.
> SUPDESQ-141 Add confirmation message to unpublish button

- ckanext/qdes_schema/blueprint.py
- ckanext/qdes_schema/constants.py
- ckanext/qdes_schema/helpers.py
- ckanext/qdes_schema/jobs.py
- ckanext/qdes_schema/templates/admin/config.html
- ckanext/qdes_schema/templates/package/snippets/unpublish_external_dataset.html
This release includes:
[SUPDESQ-111: Publish to Queensland Government Closed Data Portal](https://salsadigital.atlassian.net/browse/SUPDESQ-111)
> Release: Publishing to QLD CDP 

- ckanext/qdes_schema/templates/package/search.html
- ckanext/qdes_schema/templates/snippets/search_form.html
The new Activity extension already override the same block, adding workaround to make our customisation works.
> [SUPDESQ-173] fix ext to be compatible with 2.11.2
