ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html, ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html, ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-115
- it will throw an error when one of the values is empty.
- if both values are empty or filled, it won't throw an error
- if start < end date, it will throw an error.
- added subheading
- modify the output to include subheading on the field label
=> [DDCI-115] - added temporal date fields

ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/templates/scheming/form_snippets/datetime_tz.html, ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-119
so the date and time picker default to browser, I tested on other browsers it gives different results.
so if we want to capture down to seconds, need to implement a new time picker here, I assume another 2hrs will be enough (using default style provided by the js lib), 
maybe this simple one https://www.jonthornton.com/jquery-timepicker/ 
- if the creation date is empty, it will set by the current date-time on BE
- both release and last modified need to be >= creation date, otherwise, error raise
=> [DDCI-119] - added creation, release and last modified fields

ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/templates/admin/config.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_hidden_json.html, ckanext/qdes_schema/validators.py, requirements.txt
https://it-partners.atlassian.net/browse/DDCI-118
- it requires geojson lib https://pypi.org/project/geojson/,  the PR here https://github.com/salsadigitalauorg/qdes_ckan-29_lagoon/pull/1
- all geojson will be validated either it is valid geojson or not using above lib.
values I used for the test are below:
Lower left  
{ "coordinates": [ 143.360595703125, -23.02918734674458 ], "type": "Point" }
Upper right 
{ "coordinates": [ 144.34936523437497, -22.31958944283391 ], "type": "Point" }
Centroid
{ "coordinates": [ 143.89892578125, -22.735656852206482 ], "type": "Point" }
with geometry since it has no validation I put random geojson.
the points below are the above values.
the spatial field is generated based on the points, 
{ "coordinates": [ [ [ 143.360596, -22.319589 ], [ 144.349365, …
=> [DDCI-118] - added spatial fields and its validation

ckanext/qdes_schema/templates/scheming/display_snippets/datetime_tz.html
https://it-partners.atlassian.net/browse/DDCI-119
python date offset is returning +0700 without `:` so I did something on template level.
=> [DDCI-119] - added correct date format

ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/qdes_presets.json
QDCAT Metadata model - Dataset - Contacts and responsibilities
https://it-partners.atlassian.net/browse/DDCI-11
[- Added dataset metadata for contacts and responsibilities](https://github.com/salsa-nathan/ckanext-qdes-schema/commit/8c8de430b6c81db825744b9a8221b86cdafc016c)
[- Added  "choices_helper": "scheming_vocabulary_service_choices" to preset "controlled_vocabulary_single_select"](https://github.com/salsa-nathan/ckanext-qdes-schema/commit/246e530c026b18bf5057bc21b505e2503c0c41ad)
@salsa-nathan Created this branch from `feature/DDCI-117-Description-paramater-pair-fields` to use the multi_group functionality which is still in PR (https://github.com/salsa-nathan/ckanext-qdes-schema/pull/11) and has not been merged into develop. Hence why it's showing a lot more file changes where it …
=> QDCAT Metadata model - Dataset - Contacts and responsibilities

ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/validators.py
@salsa-nathan this issue because of the `raise` statement inside try-except block. so I split the try-except to load the json and to validate the geometry.
other changes, I changed the preset from `json_object` to textarea. somehow json_object is returning `dict` instead of a string when doing validation on the `resource` form. and return string on `package` form. I think when we didn't have custom resource form it works just fine, so it maybe a regression issue because of custom resource form.
=> fix json exception on geometry validation

ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/templates/scheming/display_snippets/controlled_vocabulary_single_select.html, ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_text_url.html, ckanext/qdes_schema/templates/scheming/display_snippets/qdes_text_url.html, ckanext/qdes_schema/templates/scheming/display_snippets/text.html, ckanext/qdes_schema/templates/scheming/form_snippets/textarea.html, ckanext/qdes_schema/templates/snippets/license.html
https://it-partners.atlassian.net/browse/DDCI-12
https://it-partners.atlassian.net/browse/DDCI-10
- with license_id, it seems the default template render it on left hand side, so I just update to print the label as link.
=> [DDCI-12] - added right and licensing fields

ckanext/qdes_schema/fanstatic/autocomplete.js, ckanext/qdes_schema/fanstatic/repeating-fields.js, ckanext/qdes_schema/helpers.py, ckanext/qdes_schema/logic/action/get.py, ckanext/qdes_schema/logic/helpers/relationship_helpers.py, ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/qdes_presets.json, ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_group.html, ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/select.html, ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/text.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_select.html, ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-9
- Added new metadata fields: series_or_collection, related_datasets, related_resources, cited_in
- Added new validators for related_datasets and related_resources
- Added new helper 'qdes_relationship_types_choices'
- Added action override for 'package_autocomplete' to return only public datasets
- Added 'createSearchChoice' option for autocomplete to allow or disallow user to entering new choice options. Similar to creating tags
- Added new 'qdes_multi_group.html' template to group metadata elements together
- Added new snippets for multi group elements
=> [DDCI-9] QDCAT Metadata model - Dataset - Related and lineage

ckanext/qdes_schema/fanstatic/autocomplete.js, ckanext/qdes_schema/helpers.py, ckanext/qdes_schema/logic/action/get.py, ckanext/qdes_schema/logic/action/update.py, ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/qdes_dataservice.json, ckanext/qdes_schema/qdes_presets.json, ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/text.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html
- Added new metadata for dataservice 'related_services' and 'related_resources'
- Refactored code for 'related_resources' into new preset 'related_resources_multi_group'
- Added new options for dataset autocomplete to filter on dataset_type and ignore own dataset id
=> [DDCI-121] QDCAT Metadata model - Data Service - Related and lineage

ckanext/qdes_schema/fanstatic/autocomplete.js, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/qdes_dataservice.json, ckanext/qdes_schema/qdes_presets.json, ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_group.html, ckanext/qdes_schema/templates/scheming/display_snippets/qdes_secure_vocabulary_text.html, ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/text.html, ckanext/qdes_schema/templates/scheming/form_snippets/text.html
This PR includes the following stories:
https://it-partners.atlassian.net/browse/DDCI-41
https://it-partners.atlassian.net/browse/DDCI-43
https://it-partners.atlassian.net/browse/DDCI-215
- Added new preset for 'qdes_secure_vocab_service_autocomplete'
- Added new preset to field 'contact_point'
- Added new display snippet for 'qdes_secure_vocabulary_text.html'
- Added minimumInputLength to 'autocomplete.js'
=> Controlled vocabulary - Contacts and responsibilities

ckanext/qdes_schema/blueprint.py
- The `related_datasets` blueprint function was expecting `id` to be a CKAN UUID but it can also be passed a CKAN package.name
- This change allows the function to accept either and does the `package_show` lookup first before continuing
=> [DDCI-96] Adjusted `related_datasets` blueprint function

ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html
https://it-partners.atlassian.net/browse/DDCI-232
The issue:
in file `ckan/ckan_core/ckan/views/resource.py:203`, the `data_provided` variable is always return True.
so that the conditional statement on 211 never executed.
the code then jump to 248, the try catch block, here either create or update resource, and it is always create.
since this is on the core ckan, it maybe built like this?
the workaround, I added a custom button with a link back to the edit package.
=> [DDCI-232] - prevented multiple resourse to be added when clicking previous btn

.gitignore, ckanext/qdes_schema/logic/action/get.py
- Changed the `all_relationships` function in `ckanext-qdes-schema/ckanext/qdes_schema/logic/action/get.py` to utilise database configuration from the CKAN `.ini` file.
=> [DDCI-16] Use config for raw query

ckanext/qdes_schema/fanstatic/autocomplete.js, ckanext/qdes_schema/qdes_ckan_dataset.json
https://it-partners.atlassian.net/browse/DDCI-210
@MarkCalvert this to remove tooltips on secure vocab. also, it fixes the issue where the tooltip still visible after we select the option.
=> [DDCI-210] - removed tooltip from vocab autocomplete

ckanext/qdes_schema/dataqld_dataset.json, ckanext/qdes_schema/fanstatic/iso-8601-duration.js, ckanext/qdes_schema/fanstatic/repeating-fields.js, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/qdes_dataservice.json, ckanext/qdes_schema/qdes_presets.json, ckanext/qdes_schema/qspatial_dataset.json, ckanext/qdes_schema/sir_dataset.json, ckanext/qdes_schema/templates/package/metadata.html, ckanext/qdes_schema/templates/package/schema_validation.html, ckanext/qdes_schema/templates/scheming/form_snippets/datetime_tz.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_duration.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_markdown.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_select.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_textarea.html, ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-139
- the issue is mostly in multi field, where the id is on the hidden field.
- with `related_resources_multi_group` field, I override the validator as we don't need this field on the external service.. yet.
- also fix small bugs on 
-- https://it-partners.atlassian.net/browse/DDCI-285
-- https://it-partners.atlassian.net/browse/DDCI-350
-- https://it-partners.atlassian.net/browse/DDCI-377
-- https://it-partners.atlassian.net/browse/DDCI-374
-- https://it-partners.atlassian.net/browse/DDCI-299
-- https://it-partners.atlassian.net/browse/DDCI-352
-- https://it-partners.atlassian.net/browse/DDCI-383
-- https://it-partners.atlassian.net/browse/DDCI-384
when I modify `qdes_ckan_dataset.json`, I also made the similar changes to the other scheming …
=> [DDCI-139] - fix anchor issues for repeater field

ckanext/qdes_schema/auth.py, ckanext/qdes_schema/plugin.py
This patch fixes an issue where the `data_service_admin_only` function would let org admin, editor and member users access and manage datasets and data services they did not have permission for.
=> [PATCH] Chained data services auth overrides.

ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/templates/scheming/package/snippets/additional_info.html
- Removed `version` field from dataset metadata schema JSON configuration file
- Changed `View all metadata` link to point to dataset name, not CKAN ID.
=> [DDCI-670] Remove `version` field

ckanext/qdes_schema/helpers.py, ckanext/qdes_schema/logic/helpers/relationship_helpers.py, ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/templates/snippets/collection.html
- Added `try ... except` to `get_package_dict` helper function to avoid internal server error on exception (e.g. `NotAuthorized`)
- Added new helper method `get_collection_parent_title` to `logic/helpers/relationship_helpers.py`
- Adjusted display of collection(s) snippet in cases where user not authorised to see collection parent dataset
=> [DDCI-690] Remediation for displaying deleted collection parent

ckanext/qdes_schema/blueprint.py
- Added context to `package_show` call in `related_datasets` blueprint method
=> [DDCI-702] Dataset's Related Datasets tab is not being populated

ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html, ckanext/qdes_schema/validators.py
https://it-partners.atlassian.net/browse/DDCI-432
when multigroup has `field_groups` in the error dict, the template will place the error on specific field group index.
```
errors[key] = [
'First index of array will appear on the top screen', 
{'field_groups': [
{'field_1': 'field error', 'field_2': 'error', 'group': 'group is for error in that field group index'}
]}
]
```
AC
not requested in AC, but these changes is needed to accommodate above.
=> [DDCI-432] - enhanced error message for multi group field

ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/validators.py
- Don't run the Package `after_update` method when adding or editing a resource
- Don't run the `qdes_validate_related_resources` method when adding or editing a resource
=> [DDCI-699] Incorrect related_resources error

ckanext/qdes_schema/fanstatic/style.css, ckanext/qdes_schema/logic/action/update.py, ckanext/qdes_schema/qdes_dataservice.json, ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html
https://it-partners.atlassian.net/browse/DDCI-727
https://it-partners.atlassian.net/browse/DDCI-728
so the issue is `data-qld` dataservive has missing dataset that will fail the validation (via API or via get_action)
https://ckan.develop.qdes-ckan.au2.amazee.io/api/3/action/package_show?id=data-qld
`
"related_resources": "[{\"resource\": {\"id\": \"a6a8668f-f6e9-4682-9c2c-1c1a75627057\", \"text\": \"QSpatial\"}, \"relationship\": \"unspecified relationship\"}, {\"resource\": {\"id\": \"26989519-a87e-4778-b630-62b3d0ac951d\", \"text\": \"Data Service - DDCI-392 - Service A [Deleted]\"}, \"relationship\": \"Is Format Of\"}]",
`
re-saving the data-qld via ui will fix the issue or remove manually via API request. you maybe want to clean that before smoke test it
in this PR I also updated …
=> [DDCI-727] - prevented get_action to raise an exception

ckanext/qdes_schema/helpers.py
https://it-partners.atlassian.net/browse/DDCI-780
in this PR, 
- get_related_object_or_url has `resource` variable with value: `[{"resource": {"id": null}, "relationship": "Replaces"}]`
- the exception is not handling it well
- if there is an exception, `object_package_id, url` variables both will return None, 
- the parent function who call this function already have a check for this variables.
- so it won't break the save process.
=> [DDCI-780] - improved exception handling

ckanext/qdes_schema/blueprint.py
in some cases, `metadata_contact_point` is empty.
=> [DDCI-140] - fix missing element on xml

ckanext/qdes_schema/blueprint.py
the issue was on few datasets, the `metadata_contact_point` field and data is missing, confirmed via API too.
it maybe an issue related to the indexing which I have PR here, https://github.com/salsadigitalauorg/ckanext-qdes-schema/pull/182
`spatial_representation` and `spatial_datum_crs `already added underneath this removed block.
=> [DDCI-140] - updated xml export

ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/templates/package/export/XML (ISO-19139).xml.j2, ckanext/qdes_schema/validators.py
I switched the `is_positive_integer` to custom validator, because if the value is `None`, it throws an error.
`qdes_validate_positive_integer` is similar as core `is_positive_integer`, except I added more check if `None`.
=> [DDCI-140] - added check for missing license_id

ckanext/qdes_schema/templates/scheming/display_snippets/qdes_multi_group.html
Update logic to only include snippet 'qdes_secure_vocabulary_text.html' if the alt_search_display parameter does not exist in the API URL
=> [SUPDESQ-22] Defects - The Other Responsible party field is no longer displaying the assigned name

ckanext/qdes_schema/helpers.py
https://salsadigital.atlassian.net/browse/SUPDESQ-19
the dataqld can't be accessed, as per I wrote this PR, I am rebuilding it, I will have a quick test again tomorrow.
https://dashboard.amazeeio.cloud/projects/dataqld-ckan/dataqld-ckan-develop/deployments
I keep the old value for backward compatibility, but let me know if this is not needed.
in my case, when I am running the sql script, before the solr reindex finish, the data still not updated.
=> [SUPDESQ-19] - updated license_id

ckanext/qdes_schema/validators.py
https://salsadigital.atlassian.net/browse/SUPDESQ-25
added support to throw an error when adding empty string as array
`[\"\"]` or `[\" \"]`
=> [SUPDESQ-25] - added support for validating empty json array

ckanext/qdes_schema/fanstatic/spinner.js, ckanext/qdes_schema/templates/package/edit_base.html, ckanext/qdes_schema/templates/package/resource_edit_base.html, ckanext/qdes_schema/templates/scheming/package/snippets/package_form.html, ckanext/qdes_schema/templates/scheming/package/snippets/resource_form.html, ckanext/qdes_schema/templates/snippets/loader.html
https://salsadigital.atlassian.net/browse/SUPDESQ-47
I have to refactor the js solution, the spinner was depending on the jquery.
the issue is, jquery or js file tends to load late,
I moved to use html instead, so we can get the html element before the jquery finish to load.
and use jquery to remove it once the load is finished.
=> [SUPDESQ-47] moved loader to snippets

ckanext/qdes_schema/templates/scheming/form_snippets/field_groups/text.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_group.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_multi_text.html, ckanext/qdes_schema/templates/scheming/form_snippets/qdes_tree_multi_group.html
Fixed dataset autocomplete bug where g.controller was `qdes-schema` for a dataset type instead of `dataset`.
Updated to use `object_type` template variable instead to get the correct dataset type value
=> [SUPDESQ-95] Related relationship bug fix

ckanext/qdes_schema/dcat/profiles.py
Use .get to get value from data dict
=> [SUPDESQ-108] Defect - Export metadata records via RDF / TTL fails when Creator is empty

ckanext/qdes_schema/blueprint.py
`attachment_filename` is deprecated in newer version, this is preventing the download metadata
=> [SUPDESQ-173] replaced deprecated attachment_filename parameter

ckanext/qdes_schema/assets/autocomplete.js, ckanext/qdes_schema/plugin.py, ckanext/qdes_schema/qdes_ckan_dataset.json, ckanext/qdes_schema/qdes_presets.json, ckanext/qdes_schema/validators.py
This pull request introduces enhancements to the CKAN QDES schema extension, focusing on improving organization-based filtering, optimizing code, and refining validation logic. The most significant changes include adding support for organization-specific autocomplete functionality, refactoring code for better maintainability, and updating validation logic for secure vocabulary checks.
* Updated `qdes_autocomplete` fields to include an `org_id` parameter in their `data-module-source` URLs to support organization-specific filtering in autocomplete functionality (`ckanext/qdes_schema/assets/autocomplete.js`, `ckanext/qdes_schema/qdes_ckan_dataset.json`, `ckanext/qdes_schema/qdes_presets.json`). [[1]](diffhunk://#diff-5eb564ca706804b9a01df5b5618772bec6a11526db75e8b2128bdf678844b074R159-R161) …
=> [SUPDESQ-193] Active Directory Integration
